### ISSUE TITLE
Button Link hero image is not aligned correctly 

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/stanford_decanter#12]
On Page https://opensource.su.domains/ link with class button is off to the left, should be consistent with alignment  configured in text
 
<img width="1168" alt="Screenshot 2024-11-20 at 10 56 58 AM" src="https://github.com/user-attachments/assets/ecb0450b-a4cc-474c-a15b-71faf70b4b98">

**Comment by ronan** [comment]
Buttons will be 'inline-block' in the next release which will fix this issue.
