### ISSUE TITLE
Paragraphs grid is broken

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/stanford_decanter#13]
https://opensource.su.domains/basic-page-paragraphs

Cards are showing very narrow and do not respect 2/3/4 cards setting.  Might be related to grid in paragraphs classes

`.paragraphs-item paragraphs-item-aplenty-cards paragraphs-item-aplenty-cards paragraphs-item-full paragraphs-item-3 aplenty-cards aplenty-card-plain`

<img width="1434" alt="Screenshot 2024-11-20 at 1 10 21 PM" src="https://github.com/user-attachments/assets/b644f299-bbcf-4b34-bbb2-26f2137591ef">

**Comment by ronan** [comment]
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/4a8612cc-dbec-4ff3-ae92-00f50dd66b07">
 
Fixed in next release

**Comment by irinaz** [comment]
thank you, looks great!
