### ISSUE TITLE
Exposed filters styles

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/stanford_decanter#15]
Exposed filters should have same styles consistent with documentation 

https://opensource.su.domains/events/past-events

Example 
https://cars.stanford.edu/datadriven/search?combine=&organization=&data_set_type=108
<img width="1131" alt="Screenshot 2024-11-25 at 2 14 28 PM" src="https://github.com/user-attachments/assets/370d2b45-cbb1-408c-b135-ee07e9bac154">

**Comment by ronan** [comment]
<img width="665" alt="image" src="https://github.com/user-attachments/assets/6b239203-dc01-4727-bd2a-08f94b7a46c6">

More consistent in latest version
