### ISSUE TITLE
Use github actions to add extra components to release zip

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/stanford_decanter#2]
While listening to the, Backdrop weekly development meeting for June 13, [discussion](https://www.youtube.com/watch?v=CTPd63wSpAg&t=175s) on the Stanford Decanter Theme, it was interesting to hear that github actions can be used to build the additional required components and include them in the release zip. This would mean the theme would be usable on download by anyone, without extra effort. Is this worth further consideration?

**Comment by klonos** [comment]
For clarity: what needs to be done is to use GitHub actions to "inject" the build assets into the .zip that is built with each project release - these assets will NOT be added to the codebase (it should be kept "clean" in order to not cause problems for developers and the maintainers of the theme).

**Comment by herbdool** [comment]
Here's some info on the build process https://tailwindcss.com/docs/installation. As I was saying, any change to any style to adapt to a specific site requires running npx. So I don't think GitHub actions will provide much value.

**Comment by irinaz** [comment]
@izmeez , theme has been updated to contain compiled css.
