### ISSUE TITLE
Color Settings not fully applied

### ISSUE THREAD

**Issue by vclewis** [backdrop-contrib/stanford_decanter#6]
I've adjusted all colors in the theme to match the brand colors of my site.

However, I've noticed on the second menu level, there is still red color, when you're on a subpage the menu reverts to the Stanford color and also buttons are still the bright red. 
<img width="611" alt="Screenshot 2024-11-08 at 10 04 17 AM" src="https://github.com/user-attachments/assets/d6cc3945-9055-4465-98ab-a34c02b6f8cf">
<img width="962" alt="Screenshot 2024-11-08 at 10 05 23 AM" src="https://github.com/user-attachments/assets/d47e208c-da77-49b0-ad9d-97f677b60b77">

**Comment by ronan** [comment]
The latest dev version simplifies and fixes the custom color settings:

<img width="356" alt="image" src="https://github.com/user-attachments/assets/0cebade4-6ae7-4814-aaf4-b7ba82e7a88f">
