### ISSUE TITLE
Button color inside content 

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/stanford_decanter#7]
Currently we have code   that makes link with class btn white text
.l-content a.btn, .l-content a.button {
    color: #fff;
}
we also need css where link inside button has white text 
.l-content  btn a, .l-content  button a {
    color: #fff;
}
<img width="1500" alt="Screenshot 2024-11-08 at 1 32 36 PM" src="https://github.com/user-attachments/assets/cef62df6-4bf1-45da-933a-679eff018a0c">

**Comment by ronan** [comment]
<img width="416" alt="image" src="https://github.com/user-attachments/assets/9c105e64-922d-4b65-a624-7629d8f54102">

This should be fixed in the latest 2.x branch and will be in the next 2.x release
