### ISSUE TITLE
Errors in header layout and styling

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/stanford_decanter#8]
In the new release there are two errors in header 

- shade box around main menu 
-  main menu and search are on the same line

 https://opensourcelab.stanford.edu/events
<img width="1498" alt="Screenshot 2024-11-08 at 1 39 48 PM" src="https://github.com/user-attachments/assets/b52eddcb-e57e-4ee0-9b55-82791a1e5ed5">

Here is correct styles/layout - we had them correct in previous release https://dev-cars-su-bd.pantheonsite.io/
<img width="1195" alt="Screenshot 2024-11-08 at 1 44 20 PM" src="https://github.com/user-attachments/assets/e0d18901-d974-47eb-95fd-3e7f66d3f9ac">

**Comment by ronan** [comment]
This should be fixed in both the 1.x and 2.x branches
