### ISSUE TITLE
Search block won't display for anonymous users

### ISSUE THREAD

**Issue by johnquest** [backdrop-contrib/stanford_decanter#9]
First of all, it's good to see Decanter. Looks great. I have the search form block placed in the header search/links region but it only displays when I'm logged into BD. I have no visibility conditions set but I did add one for anonymous users but still won't show. Any ideas?

**Comment by irinaz** [comment]
@johnquest , how are permissions for search module set?

**Comment by johnquest** [comment]
Ah that's it. Thanks
